### ISSUE TITLE
Let me get the list of tags or better, add proper metadata, please!

### ISSUE THREAD

**Issue by oderwat** [nats-io/jwt#200]
We want to store "meta" style information in the creds file. This would be easy by using a tag with a prefix. We would want to use if, for example to add a `account_PRODUCT-BETA` because showing the issuer account public key, does not help much if you don't have a list of all of them that translate the name to a "user readable" name. I saw #101 which seems to have a similar purpose. As is, we need to check with "Contains" for all possible values. There are quite a lot of use case where it would be nice to be able to store information in the creds like the email of the user or some IDs from other systems. It would also be nice because you could show the tags of the claims with "the" standard package for handling these JWTs.

EDIT: We parse it now from the JWT string, while doing that it struck me that the tags are also forced to be lower case. I do not really understand what all of these restrictions are about. I would suggest adding a proper way to add string indexed string metadata to the user JWT.

**Comment by aricart** [comment]
The restrictions on lower-case are to simplify matching and other sorts of things - we have seen use tags quite frequently (and we ourselves use them - nats-server uses them internally I believe). We usually specify key/value relationships as I have shown above. We could restrict the lower-case requirements, but the format is likely not going to change because as I said above many folks  use the current tag mechanism fairly extensively

**Comment by oderwat** [comment]
I want the list of the tags and not just "Contains('some_tag')".

I know that they can have tags. So if you use 'account=demo' which would be 'account:demo' for me, but that is a minor detail in the implementation. So, how do you access them using the JWT package? It does not expose them, that is what I was asking about.

For now, we use:

```
package appxnats

import (
	"encoding/json"
	"github.com/nats-io/jwt/v2"
)

type jsonData struct {
	//	Jti  string `json:"jti"`
	//	Iat  int    `json:"iat"`
	//	Iss  string `json:"iss"`
	//	Name string `json:"name"`
	//	Sub  string `json:"sub"`
	Nats natsData `json:"nats"`
}

type natsData struct {
	//	Pub           interface{} `json:"pub"`
	//	Sub           interface{} `json:"sub"`
	//	Subs          int         `json:"subs"`
	//	Data          int         `json:"data"`
	//	Payload       int         `json:"payload"`
	//	IssuerAccount string      `json:"issuer_account"`
	Tags []string `json:"tags"`
	//	Type          string      `json:"type"`
	//	Version       int         `json:"version"`
}

// GetTagsFromClaims extracts the tags from a nats JWT
func GetTagsFromClaims(claims jwt.Claims) ([]string, error) {
	data := jsonData{}
	err := json.Unmarshal([]byte(claims.String()), &data)
	if err != nil {
		return nil, err
	}
	return data.Nats.Tags, nil
}
```
