### ISSUE TITLE
allow deny perms + queue permissions separated by a space

### ISSUE THREAD

**Issue by aricart** [nats-io/jwt#67]
In my opinion, the above is a bug, that just does the right thing because the protocol just happens to map to that. This is the same as `nats-sub "hello world"` and then `nats-pub "hello world"` which is a common issue I have seen in API/cli use more than a few times.

https://docs.nats.io/developing-with-nats/receiving/queues#queue-permissions, effectively documents this 'bug' and turns  allow/deny has a complex condition, which allows spaces to "map" it into a subject+queuename, but spaces are not allowed on subjects, so there has to be a better way of expressing queue names that clients can use while allowing validation of subjects to work correctly.

If you:

```
nsc add operato r O
nsc add account A
nsc add user U --allow-pub "foo bar"
nsc validate
# NSC prints validation errors
```

Now parallel to this discussion is how we express this properly on the CLI. Currently, the subject is supposed to be a string, and it cannot have spaces as per the subject specification. This means that if the user wants to specify a queue, it should be explicit. To map it into a string, they would have to enter JSON `{"subject": "foo", "queue": "bar"}`, having the entry be JSON.

Finally, I am wondering why this is even needed. The first assertion is that if the client can subscribe to the subject it can already read the data, so the issue here is a bad client joining the queue group. So we need to protect the queue group, likely the solution should be specifying whether the client can connect to a queue group or not, and also, likely queue group boundaries should be at the account level, and not cross accounts. This way clients can be sandboxed on the account insuring that the right group cannot be spoofed, while allowing same account queue groups to join properly. Possibly, munging the queue names with their account's public key would be sufficient to make this happen.

**Comment by aricart** [comment]
Really thinking that the solution should be a single property on the user, that specifies whether it can make a queue subscription or not. This will prevent a subscriber from joining a service group, which I think is the intention of this.

**Comment by derekcollison** [comment]
There is an additional piece that I did not have time for but is needed to complete the story which is the opposite of the allow-response, meaning deny-response. So you can form observers but can not participate in the service itself.

**Comment by derekcollison** [comment]
Since nsc is not a fast path, why wouldn't this fail?

`nsc add user U --allow-pub "foo bar"`

We should have a inline validation for subjects here IMO.

**Comment by wallyqs** [comment]
Thanks @aricart for the report... fix is here to prevent the server to run into the validation issue once connecting to the server: https://github.com/nats-io/jwt/pull/68
Currently `nsc` does allow to generate credentials with qsubs permissions already, so we need to change it so that `--allow-pub` and `--allow-pubsub` throw an error in case of invalid subjects as the jwt does and also update `--allow-sub` as well in case of invalid queue groups.
